apiVersion: apps/v1
kind: Deployment
metadata:
  name: extended-deployment
  labels:
    app: web
  annotations:
    description: example
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: web
    spec:
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      containers:
        - name: kuard
          image: 'gcr.io/kuar-demo/kuard-amd64:blue'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: ENV_VARIABLE
              value: Value
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 500Mi
              cpu: 500m
